apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ghswansea/bank-app-project-demo'
    targetRevision: main
    path: helm/bank-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bank-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

