name: Hello CI

on: [push]

jobs:
    hello-hi:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hi
              run: echo "Hello, Hi!"
    
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
